palm_api_key = "AIzaSyBXIBEKgqLHP_Ou0WtERFfWr9NJRVxfUSs"
groq_api_key = "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"
palm_api_keyd = "AIzaSyBXIBEKgqLHP_Ou0WtERFfWr9NJRVxfUSs"
gdroq_api_key = "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"
